@startuml get_appointment
actor patient
participant homePage
participant resultPage
participant appointmentPage

patient -> homePage ++ :  choose the specialty and the city of the practitioner
homePage -> resultPage ++ : filter practitioners by specialty and city name
patient <- resultPage : display the result of practitioners list and their disposable
patient -> resultPage : choose an appointment time of a practitioner
resultPage -> appointmentPage : validate request
patient <- appointmentPage : display the message of success to get the appointment 

@enduml